force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Jersey_Number__c.field-meta.xml
<CustomField>
    <fullName>Jersey_Number__c</fullName>
    <label>Jersey Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Batsman</fullName>
            </value>
            <value>
                <fullName>Bowler</fullName>
            </value>
            <value>
                <fullName>WicketKeeper</fullName>
            </value>
            <value>
                <fullName>Allrounder</fullName>
            </value>
            <value>
                <fullName>12thMan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Playing_Eleven__c/Playing_Eleven__c.object-meta.xml
<CustomObject>
    <label>Playing Eleven</label>
    <nameField>
        <label>Playing Eleven Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playing Elevens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playing_Eleven__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player</label>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Playing Elevens</relationshipLabel>
    <relationshipName>Playing_Elevens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playing_Eleven__c/fields/Teamid__c.field-meta.xml
<CustomField>
    <fullName>Teamid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Playing Elevens</relationshipLabel>
    <relationshipName>Playing_Elevens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Script1_Team.cls
public class Script1_Team {
    public static void main(){
        List<Team__c> team_list=new List<Team__c>();
        Team__c team_o=new Team__c();
        team_o.name='xyz';
        team_o.logo__c='hjkdhf';
        team_o.Country__c='india';
        team_list.add(team_o);
        insert team_list;  
        
         List<Player__c> p_name = new List<Player__c>();
         Player__c p = new Player__c();   
          p.name='deepak';
          p.Jersey_Number__c=10;
          p.Type__c='batsman';
          p_name.add(p);  
         insert p_name;
        
         List<Playing_Eleven__c> pn=new list<Playing_Eleven__c>();
             Playing_Eleven__c pn_obj=new Playing_Eleven__c();
              pn_obj.Player__c=p.id;
               pn_obj.Teamid__c= team_o.id;
               pn.add(pn_obj);
               insert pn;
                              
    }    
}