force-app/main/default/objects/House_Hold_Link__c/House_Hold_Link__c.object-meta.xml
<CustomObject>
    <label>House Hold Link</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>House Hold Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/House_Hold_Link__c/fields/Currentnetvalue__c.field-meta.xml
<CustomField>
    <fullName>Currentnetvalue__c</fullName>
    <label>Current Net value</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/House_Hold_Link__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Household__c</referenceTo>
    <relationshipLabel>House Hold Links</relationshipLabel>
    <relationshipName>House_Hold_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/House_Hold_Link__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/House_Hold_Link__c/fields/Institution_Id__c.field-meta.xml
<CustomField>
    <fullName>Institution_Id__c</fullName>
    <label>Institution Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/House_Hold_Link__c/fields/Last_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Update__c</fullName>
    <label>Last  Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Household__c/Household__c.object-meta.xml
<CustomObject>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Household__c/fields/Household_Id__c.field-meta.xml
<CustomField>
    <fullName>Household_Id__c</fullName>
    <label>Household Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAccountDatacontroller.cls
public class GetAccountDatacontroller {
    
    @AuraEnabled
    public static string getDataAccountDataFromBlueLeaf(String RecordId){
        try{
        System.debug('RecordId====> '+RecordId);
        String resp = '';
        String ApiKey ='61c1b6069e26ddffb40c5da130d0171a93a69d24aaba3ca6b897f49e2b89eafc';
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        household__c hs = [Select Household_Id__c from Household__c where Id=:RecordId];
        req.setEndpoint('https://secure.blueleaf.com/api/v1/households/'+hs.Household_Id__c+'.xml');
        String EncodedAccessToken =  EncodingUtil.Base64Encode(Blob.valueOf(ApiKey));
        req.setHeader('Authorization','Basic '+EncodedAccessToken);
        req.setMethod('GET');
        System.debug('REQUEST');
        httpresponse res = new HttpResponse();
        res=http.send(req);
        if(res.getStatusCode()==200){
        list<XmlParsingForHouseHoldAccounts.AccountData>Accountdatalist = XmlParsingForHouseHoldAccounts.ParseAccountsData(res.getBody());
            GetAccountDatacontroller.CreatelistOfAccountData(Accountdatalist,RecordId);
            resp = resp+'Successful';
        }
        else{
            resp = resp+'Unsuccessful';
        }
        return resp;
      }
        catch(Exception e)
        {
            System.debug('Exception====> '+e.getLineNumber()+'Message==> '+e.getMessage());
            return e.getMessage();
        }
      //  return resp;
    }
    
    @AuraEnabled
    public static void CreatelistOfAccountData(list<XmlParsingForHouseHoldAccounts.AccountData> Aclist,String RecordId){
        
        list<House_Hold_Link__c> HouseHoldlinklist = new list<House_Hold_Link__c>();
        for(XmlParsingForHouseHoldAccounts.AccountData xv : Aclist)
        {
            House_Hold_Link__c hh = new House_Hold_Link__c();
            hh.Account_Number__c = xv.accountNumber;
            hh.Account_Type__c = xv.accTypename;
            hh.Currentnetvalue__c = Decimal.valueOf(xv.currentNetvalue);
            hh.Id__c = xv.id;
            hh.Institution_Id__c = xv.institutionId;
            hh.Institution_Name__c = xv.institutionName;
            hh.Period__c = Date.valueOf(xv.period);
            hh.Value__c = Decimal.valueOf(xv.value);
           // hh.Last_Update__c = Datetime.valueOf(xv.lastupdate);
            hh.Name = xv.name;
            hh.Household__c = RecordId;
            HouseHoldlinklist.add(hh);
        }
        Database.upsert(HouseHoldlinklist, House_Hold_Link__c.Id__c);
        
        
    }
  
}