force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/AccountType__c.field-meta.xml
<CustomField>
    <fullName>AccountType__c</fullName>
    <label>AccountType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account__c/fields/SyncToken__c.field-meta.xml
<CustomField>
    <fullName>SyncToken__c</fullName>
    <label>SyncToken</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SerilizeAccountUpdate.cls
public class SerilizeAccountUpdate {

    public static String serAccupdate(List<Account__C> accList){
      wrapperAccData wrAcdata=new wrapperAccData();
        wrAcdata.Name=accList[0].Name;
        wrAcdata.AccountType=accList[0].Accounttype__c;
        wrAcdata.Id=accList[0].ExternalId__c;
        wrAcdata.SyncToken=accList[0].SyncToken__c;
        String str=Json.serialize(wrAcdata);
        PostQuickAccData.PostAccupdateData(str);
        System.debug(str);
        return str;
    }
    
    
    public class wrapperAccData{
        public String Name;
        public String AccountType;
        public String Id;
        public String SyncToken;
        
    }
    
}