force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account__c/fields/SyncToken__c.field-meta.xml
<CustomField>
    <fullName>SyncToken__c</fullName>
    <label>SyncToken</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accountids__c/Accountids__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AccountId</label>
</CustomObject>

force-app/main/default/classes/AccountUpdation.cls
public class AccountUpdation {

    public static void updateAccount(String ids,String stoken ){
        try{
        Accountids__c acid =[select Accountid__c from Accountids__c limit 1];        
        Account__c updateAcc= new Account__c ();
        updateAcc.ExternalId__c=ids;
        updateAcc.Id=acid.Accountid__c;
        updateAcc.SyncToken__c=stoken;    
        System.debug('value are '+ updateAcc);
        update updateAcc;
            }
        catch(Exception e){
            system.debug(e.getLineNumber()+'>>>>>>>>>>>'+e.getMessage());
            }
     
    }
  
}